# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "fltk" %}
{% set version = "1.3.4" %}
{% set longversion = "1.3.4-2" %}
{% set md5 = "69128be72365cbedd1d380739f0164e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ longversion }}-source.tar.gz
  url: http://fltk.org/pub/{{ name }}/{{ version }}/{{ name }}-{{ longversion }}-source.tar.bz2
  md5: {{ md5 }}

build:
  number: 1003
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("fltk", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('expat') }}             # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]

  host:
    - zlib
    - jpeg
    - libpng
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - libxcb
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - libglu    # [linux]

  run:
    - zlib
    - jpeg
    - libpng
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - libxcb
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - libglu    # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libfltk.a  # [unix]
    - test -f $PREFIX/lib/libfltk_gl.a  # [unix]
    - if not exist %LIBRARY_LIB%\\fltk.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\fltk_gl.lib exit 1  # [win]

about:
  home: http://www.fltk.org/
  license: LGPL-2.0
  license_family: LGPL
  license_file: COPYING
  summary: 'The Fast Light Tool Kit ("FLTK", pronounced "fulltick") is a cross-platform C++ GUI toolkit'

  description: |
    FLTK (pronounced "fulltick") is a cross-platform C++ GUI toolkit for
    UNIX/Linux (X11), Microsoft Windows, and MacOS X. FLTK provides
    modern GUI functionality without the bloat and supports 3D graphics via
    OpenGL and its built-in GLUT emulation.

    FLTK is designed to be small and modular enough to be statically
    linked, but works fine as a shared library. FLTK also includes an
    excellent UI builder called FLUID that can be used to create
    applications in minutes.
  doc_url: http://www.fltk.org/documentation.php
  dev_url: http://www.fltk.org/roadmap.php

extra:
  recipe-maintainers:
    - guyer
    - matthiasdiener
